#include "graph/NodeParams.h"

#include <limits>

// 範囲と意味の出所は、各ノードの評価のコード（範囲外のエラー）と io/GraphIo.cpp の読み込み（丸め）。
// 「最長辺」はそのノードが受け取ったボリュームの中身の外接箱の最長辺（geometry/Volume.cpp の InteriorLongestSide）。
namespace rock::graph {
namespace {

constexpr double N = std::numeric_limits<double>::quiet_NaN();
using K = NodeKind;
using T = ParamType;
using C = ParamCheck;

constexpr const char* kLongest = "最長辺に対する比";

constexpr ParamOption kShapes[] = {{"box", 0, "直方体"}, {"roundedBox", 1, "角の丸い直方体"},
                                   {"sphere", 2, "球（size[0] が直径）"}, {"ellipsoid", 3, "楕円体"}};
constexpr ParamOption kSubdivisions[] = {{"4", 4, "面を4分割"}, {"8", 8, "8分割"}, {"16", 16, "16分割"}, {"32", 32, "32分割"}};
constexpr ParamOption kMeshers[] = {{"marchingTetrahedra", 0, "Marching Tetrahedra（なめらか。既定）"},
                                    {"dualContouring", 1, "Dual Contouring（角と平らな面を保つ。岩にはこちら）"}};
constexpr ParamOption kSelectModes[] = {
    {"manual", 0, "手動で選んだ片（ids）"},
    {"outer", 1, "外面（outerFaces のビット）に接する片"},
    {"region", 2, "重心が minimum〜maximum の箱に入る片"},
    {"volume", 3, "体積が minVolume〜maxVolume の片"},
    {"random", 4, "fraction の割合をランダムに"},
    {"rim", 5, "元の板の側縁に接する片（Layered Boxes 用）"},
    {"peel", 6, "露出した外周から内側へ順に欠く（fraction が進行）"}};
constexpr ParamOption kRimSides[] = {{"both", 0, "積層の両側から"}, {"top", 1, "上側から"}, {"bottom", 2, "下側から"}};
constexpr ParamOption kBooleanOps[] = {{"union", 0, "和"}, {"intersection", 1, "交差"}, {"difference", 2, "差（A − B）"}};
constexpr ParamOption kCutScopes[] = {{"global", 0, "形全体を平面で切る"}, {"local", 1, "局所的に欠く（radius の範囲）"}};
constexpr ParamOption kCutDistributions[] = {{"isotropic", 0, "向きをばらばらに"},
                                             {"directional", 1, "rotation の主方向（systems 系統）の周りに"}};
constexpr ParamOption kNoiseTypes[] = {{"smooth", 0, "なめらか"}, {"cellular", 1, "セル状（丸い盛り上がり）"},
                                      {"facet", 2, "小面（岩の割れ面らしい）"},
                                      {"pits", 3, "くぼみ（セルの内側を削り境を壁に残す。蜂の巣状の風化・タフォニ）"}};
constexpr ParamOption kSmoothModes[] = {{"smooth", 0, "なめらかにする"}, {"sharpen", 1, "角を立てる"}};
constexpr ParamOption kCloseModes[] = {{"width", 0, "幅より狭い隙間を埋める"}, {"occlusion", 1, "奥まった（遮蔽の強い）所を埋める"}};
constexpr ParamOption kShapeMaskTypes[] = {{"occlusion", 0, "遮蔽（窪み）"}, {"direction", 1, "上向き度"}, {"height", 2, "高さ"},
                                          {"valleyCurvature", 3, "曲率（谷）"}, {"ridgeCurvature", 4, "曲率（山・稜線）"}};
constexpr ParamOption kCombineOps[] = {{"multiply", 0, "積"}, {"maximum", 1, "大きい方"}, {"minimum", 2, "小さい方"},
                                       {"subtract", 3, "A − B"}, {"mix", 4, "mix で混ぜる"}};
constexpr ParamOption kFilterTypes[] = {{"blur", 0, "ぼかし"}, {"sharpen", 1, "シャープ"}, {"levels", 2, "レベル補正"}};
constexpr ParamOption kClipModes[] = {{"world", 0, "指定した高さで切る"},
                                     {"ground", 1, "形の底から embed の位置で切り、切り口を height（地面）に置く"}};
constexpr ParamOption kStructureTypes[] = {{"bands", 0, "縞: Planes の構造面の層ごとに塗る（片麻岩の縞・砂岩の色の層）"},
                                          {"veins", 1, "脈: 3D の網目の細い線（大理石・石英の脈）"}};
constexpr ParamOption kCrackSources[] = {{"inputs", 0, "Points（Voronoi 境界）か Planes（構造面）の入力に沿う"},
                                        {"shells", 1, "表面に沿う殻（シーティング・玉ねぎ状の風化）"}};
constexpr ParamOption kScatterShapes[] = {{"sphere", 0, "球"}, {"ellipsoid", 1, "楕円体（丸い礫・気泡）"},
                                         {"box", 2, "箱（角張った礫・角礫岩）"}};
constexpr ParamOption kScatterOperations[] = {{"union", 0, "和: 形を足す（埋まった礫）"}, {"difference", 1, "差: 形を抜く（気泡の穴）"}};
constexpr ParamOption kHeightmapSources[] = {{"noise", 0, "ノイズの山"}, {"image", 1, "画像（image のパス）"}};
constexpr ParamOption kMappingMethods[] = {{"uv", 0, "UV"}, {"triplanar", 1, "Triplanar（UV 不要。岩の下地に向く）"}};
constexpr ParamOption kValueSources[] = {{"constant", 0, "一定"}, {"noise", 1, "ノイズ"}, {"texture", 2, "テクスチャ"}};
constexpr ParamOption kLayerNoiseTypes[] = {{"fbm", 0, "fBm"}, {"ridged", 1, "リッジ"}, {"worley", 2, "Worley"},
                                            {"perlin", 3, "Perlin"}, {"billow", 4, "Billow"}, {"cracks", 5, "ひび"}};
constexpr ParamOption kChannels[] = {{"baseColor", 0, "色"}, {"normal", 1, "法線"}, {"surface", 2, "粗さ・金属・AO"}, {"height", 3, "ハイト"}};

constexpr ParamDefinition kParams[] = {
    // --- Base Shape ---
    {K::BaseRock, "baseRock.shape", T::Enum, N, N, "", "形状", "母岩の形", C::Error, kShapes},
    {K::BaseRock, "baseRock.size", T::Float3, 0.001, 1000, "m", "寸法 X/Y/Z", "外接箱の寸法。sphere は size[0] が直径", C::Error},
    {K::BaseRock, "baseRock.subdivisions", T::IntEnum, 4, 32, "", "面の分割数", "1 面あたりの分割数（4 / 8 / 16 / 32 のどれか）", C::Error, kSubdivisions},
    {K::BaseRock, "baseRock.roundness", T::Float, 0, 1, "短辺の半分に対する比", "丸み", "roundedBox の角の丸み", C::Error},
    {K::BaseRock, "baseRock.noiseStrength", T::Float, 0, 0.15, "原点からの距離に対する比", "ノイズ強度", "表面を放射方向に揺らす量。0 で揺らさない", C::Error},
    {K::BaseRock, "baseRock.noiseScale", T::Float, 0.5, 4, "", "ノイズ細かさ", "揺らすノイズの細かさ", C::Error},
    {K::BaseRock, "baseRock.seed", T::Int, 0, N, "", "Seed", "noiseStrength > 0 のときだけ形に効く", C::None},
    // --- Random Boxes ---
    {K::RandomBoxes, "randomBoxes.count", T::Int, 1, 32, "個", "個数", "重ねる直方体の数", C::Error},
    {K::RandomBoxes, "randomBoxes.size", T::Float3, 0.1, 100, "m", "基準寸法", "最初の直方体の寸法", C::Error},
    {K::RandomBoxes, "randomBoxes.sizeVariation", T::Float, 0, 0.8, "比", "サイズばらつき", "2 個目以降を縮める割合の幅", C::Error},
    {K::RandomBoxes, "randomBoxes.spread", T::Float, 0, 0.95, "最初の直方体の半寸法に対する比", "配置の広がり", "2 個目以降の中心をずらす範囲", C::Error},
    {K::RandomBoxes, "randomBoxes.rotation", T::Float, 0, 90, "度", "回転幅", "各軸の回転の乱数の幅（±）", C::Error},
    {K::RandomBoxes, "randomBoxes.seed", T::Int, 0, N, "", "Seed", "", C::None},
    // --- To Volume / Volume to Mesh / Volume Transform ---
    {K::ToVolume, "toVolume.resolution", T::Int, 16, 128, "最長辺のセル数", "解像度", "ボリュームの細かさ。セルより細い隙間・薄片は失われる。岩 1 個なら 96〜128", C::Error},
    {K::VolumeToMesh, "volumeToMesh.method", T::Enum, N, N, "", "変換方式", "ボリュームをメッシュへ戻す方式。知らない値は marchingTetrahedra", C::Clamp, kMeshers},
    {K::VolumeTransform, "volumeTransform.position", T::Float3, -10000, 10000, "m", "移動", "倍率 → 回転 → 移動の順に原点まわりで動かす", C::Error},
    {K::VolumeTransform, "volumeTransform.rotation", T::Float3, -360, 360, "度", "回転", "Z → X → Y の順", C::Error},
    {K::VolumeTransform, "volumeTransform.scale", T::Float, 0.05, 20, "倍", "倍率", "", C::Error},
    // --- UV / ベイク ---
    {K::UvUnwrap, "uvUnwrap.resolution", T::Int, 128, 4096, "px（2 のべき乗）", "テクスチャ解像度", "読み込みで 2 のべき乗へ切り上げて丸める", C::Clamp},
    {K::UvUnwrap, "uvUnwrap.padding", T::Int, 1, 32, "px", "余白", "UV の島の間の余白", C::Error},
    {K::UvUnwrap, "uvUnwrap.quality", T::Int, 1, 4, "", "品質", "展開の品質。高いほど遅い", C::Error},
    {K::MaterialBake, "materialBake.geometryAo", T::Bool, N, N, "", "形状AOをベイク", "形の遮蔽を AO に焼き込む", C::None},
    {K::MaterialBake, "materialBake.aoDistance", T::Float, 0.001, 1000, "m", "AO距離", "", C::Clamp},
    {K::MaterialBake, "materialBake.aoStrength", T::Float, 0, 1, "比", "AO強度", "", C::Clamp},
    {K::MaterialBake, "materialBake.aoSamples", T::Int, 8, 128, "本", "AOサンプル数", "", C::Clamp},
    {K::MaterialBake, "materialBake.cageDistance", T::Float, 0.0001, 100, "m", "ケージ距離", "High 入力のハイポリを探す距離（ローポリの面から内外へ）", C::Clamp},
    // --- ピース ---
    {K::LayeredBoxes, "pieces.count", T::Int, 1, 32, "枚", "枚数", "積む板の数。下から層 0, 1, …", C::Error},
    {K::LayeredBoxes, "pieces.size", T::Float3, 0.001, 1000, "m", "寸法", "X/Z が板の広さ、Y が板厚", C::Error},
    {K::LayeredBoxes, "pieces.rotation", T::Float3, N, N, "度", "向き", "積層全体の向き（Z → X → Y）。片理・層理の傾きはここで決める", C::Error},
    {K::LayeredBoxes, "pieces.position", T::Float3, -100000, 100000, "m", "位置", "積層全体の中心", C::Error},
    {K::LayeredBoxes, "pieces.gap", T::Float, 0, 10, "m", "隙間", "板の間の隙間。To Volume のセルより狭いと繋がる", C::Error},
    {K::LayeredBoxes, "pieces.thicknessVariation", T::Float, 0, 0.8, "比", "厚さのばらつき", "", C::Error},
    {K::LayeredBoxes, "pieces.sizeVariation", T::Float, 0, 0.8, "比", "広さのばらつき", "", C::Error},
    {K::LayeredBoxes, "pieces.offset", T::Float, 0, 1000, "m", "面内のずれ", "板ごとに面内でずらす量", C::Error},
    {K::LayeredBoxes, "pieces.seed", T::Int, 0, N, "", "Seed", "", C::None},
    {K::ScatterPoints, "pieces.count", T::Int, 2, 1024, "点", "点数",
     "Mesh 入力は全体で 2〜1024。Pieces 入力は 1 片あたり 2〜512 で、片の数との積が 1024 以下", C::Error},
    {K::ScatterPoints, "pieces.planar", T::Bool, N, N, "", "面内配置", "片のローカル XZ 面に点を並べる（板を厚さ方向に貫いて割る）", C::None},
    {K::ScatterPoints, "pieces.seed", T::Int, 0, N, "", "Seed", "", C::None},
    {K::ScatterPoints, "pieces.version", T::Int, 1, 1, "", "", "アルゴリズムの版。1 のまま", C::Error, {}, true},
    {K::VoronoiFracture, "pieces.rotation", T::Float3, N, N, "度", "方向", "分割の座標系の向き（Z → X → Y）", C::Error},
    {K::VoronoiFracture, "pieces.stretch", T::Float3, N, N, "倍", "伸長 XYZ",
     "分割の座標系の伸長比。正の値で、最大/最小の比は 16 以下。大きい軸の方向に細長い片になる", C::Error},
    {K::VoronoiFracture, "pieces.version", T::Int, 1, 1, "", "", "アルゴリズムの版。1 のまま", C::Error, {}, true},
    {K::PieceSelect, "pieces.mode", T::IntEnum, 0, 6, "", "選別方法", "どの片を選ぶか。使う項目はモードで変わる", C::Error, kSelectModes},
    {K::PieceSelect, "pieces.outerFaces", T::Int, 0, 63, "ビット", "接する外面",
     "outer 用。1=+X, 2=-X, 4=+Y, 8=-Y, 16=+Z, 32=-Z の和", C::None},
    {K::PieceSelect, "pieces.seed", T::Int, 0, N, "", "Seed", "random / rim / peel 用", C::None},
    {K::PieceSelect, "pieces.minimum", T::Float3, N, N, "m", "範囲 最小", "region 用。重心の範囲（ワールド座標）。maximum 以下", C::Error},
    {K::PieceSelect, "pieces.maximum", T::Float3, N, N, "m", "範囲 最大", "region 用", C::Error},
    {K::PieceSelect, "pieces.minVolume", T::Float, 0, N, "m³", "最小体積", "volume 用。maxVolume 以下", C::Error},
    {K::PieceSelect, "pieces.maxVolume", T::Float, 0, N, "m³", "最大体積", "volume 用", C::Error},
    {K::PieceSelect, "pieces.fraction", T::Float, 0, 1, "比", "選択率 / 欠けの進行", "random / rim は選ぶ割合、peel は欠く進行", C::Error},
    {K::PieceSelect, "pieces.invert", T::Bool, N, N, "", "選択を反転", "peel では残った片を出す", C::None},
    {K::PieceSelect, "pieces.layer", T::Int, -1, N, "", "対象の層", "-1 で全層。0 以上でその層だけ（反転もその層の中）", C::Error},
    {K::PieceSelect, "pieces.rimLayers", T::Int, 0, 32, "層", "外側から何層", "rim / peel 用。0 で全層", C::Error},
    {K::PieceSelect, "pieces.rimSide", T::IntEnum, 0, 2, "", "積層の外側", "rim / peel 用", C::Error, kRimSides},
    {K::PieceSelect, "pieces.rimFalloff", T::Float, 0, 1, "比", "内側ほど弱く", "rim 用。内側の層ほど選択率を下げる", C::Error},
    {K::PieceSelect, "pieces.peelNoise", T::Float, 0, 1, "比", "ばらつき", "peel 用。欠く順序のばらつき", C::Error},
    {K::PieceSelect, "pieces.protectCore", T::Bool, N, N, "", "中心の片を保護", "peel 用。上下を覆われた中間層を守る", C::None},
    {K::PieceSelect, "pieces.grounded", T::Bool, N, N, "", "接地",
     "peel 用。下向きの外面を地面に支えられた面として扱い、そこからは欠かない（岩峰・露頭・崖の根元が残る）", C::None},
    {K::PieceSelect, "pieces.producer", T::Int, N, N, "", "", "manual の選択が指す分割", C::None, {}, true},
    {K::PieceSelect, "pieces.generation", T::String, N, N, "", "", "manual の選択が指す分割の世代", C::None, {}, true},
    {K::PieceSelect, "pieces.ids", T::FloatArray, N, N, "", "", "manual で選んだ片の ID", C::None, {}, true},
    {K::PieceFilter, "pieces.keep", T::Bool, N, N, "", "Keep", "true で選んだ片だけ残す、false で選んだ片を消す", C::None},
    {K::PieceTransform, "pieces.pose.position", T::Float3, N, N, "m", "移動", "選んだ片をまとめて動かす", C::Error},
    {K::PieceTransform, "pieces.pose.rotation", T::Float3, N, N, "度", "回転", "Z → X → Y", C::Error},
    {K::PieceTransform, "pieces.pose.scale", T::Float3, N, N, "倍", "倍率", "正の値", C::Error},
    {K::PieceTransform, "pieces.individual", T::Bool, N, N, "", "各片の重心を中心に", "false なら選択全体の重心を中心にする", C::None},
    {K::PieceTransform, "pieces.jitterPosition", T::Float3, 0, 100, "m", "ばらつき 移動",
     "片ごとに各軸 ± この範囲で乱数で動かす（ブロックのずれ・崩れた岩屑）", C::Error},
    {K::PieceTransform, "pieces.jitterRotation", T::Float, 0, 180, "度", "ばらつき 回転",
     "片ごとに自分の重心を中心に、各軸 ± この角度で乱数で回す（ブロックの傾き）", C::Error},
    {K::PieceTransform, "pieces.jitterSeed", T::Int, 0, N, "", "ばらつき Seed", "", C::None},
    {K::PieceTransform, "pieces.producer", T::Int, N, N, "", "", "", C::None, {}, true},
    {K::PieceTransform, "pieces.generation", T::String, N, N, "", "", "", C::None, {}, true},
    {K::PieceTransform, "pieces.overrides", T::FloatArray, N, N, "", "", "片ごとの個別の変換", C::None, {}, true},
    // --- ボリュームの加工 ---
    {K::VolumeBoolean, "volumeBoolean.operation", T::Enum, N, N, "", "演算", "", C::Clamp, kBooleanOps},
    {K::VolumeBoolean, "volumeBoolean.blend", T::Float, 0, 10, "m", "なめらかさ", "境目の丸みの幅", C::Error},
    {K::PlaneCuts, "planeCuts.count", T::Int, 1, 256, "枚", "枚数", "切る平面の数", C::Error},
    {K::PlaneCuts, "planeCuts.scope", T::Enum, N, N, "", "適用範囲", "", C::Clamp, kCutScopes},
    {K::PlaneCuts, "planeCuts.radius", T::Float, 0.02, 1, kLongest, "半径", "local の欠けの半径", C::Error},
    {K::PlaneCuts, "planeCuts.depthMin", T::Float, 0, 0.45, "比", "深さ 最小",
     "global は平面の法線方向の形の幅、local は半径に対する比。depthMax 以下", C::Error},
    {K::PlaneCuts, "planeCuts.depthMax", T::Float, 0, 0.45, "比", "深さ 最大", "", C::Error},
    {K::PlaneCuts, "planeCuts.distribution", T::Enum, N, N, "", "法線の分布", "", C::Clamp, kCutDistributions},
    {K::PlaneCuts, "planeCuts.systems", T::Int, 1, 3, "系統", "系統数", "directional の主方向の数", C::Error},
    {K::PlaneCuts, "planeCuts.rotation", T::Float3, -360, 360, "度", "向き", "directional の主方向", C::Error},
    {K::PlaneCuts, "planeCuts.spread", T::Float, 0, 90, "度", "ばらつき", "主方向からのずれ", C::Error},
    {K::PlaneCuts, "planeCuts.blend", T::Float, 0, 10, "m", "なめらかさ", "", C::Error},
    {K::PlaneCuts, "planeCuts.seed", T::Int, 0, N, "", "Seed", "", C::None},
    {K::PlaneCuts, "planeCuts.curvature", T::Float, 0, 1, "", "曲がり",
     "0 で平らな切り口。正なら外側に中心を置いた球で切り、えぐれた曲面の切り口（貝殻状断口）。球の半径は 最長辺 ÷ (4 × 曲がり)", C::Error},
    {K::ParallelPlanes, "parallelPlanes.rotation", T::Float3, N, N, "度", "向き", "回転した +Y が面の法線。片理なら Layered Boxes の rotation と揃える", C::Error},
    {K::ParallelPlanes, "parallelPlanes.spacing", T::Float, 0.001, 1000, "m", "間隔",
     "面の間隔。評価範囲の面は 512 枚まで（岩の大きさ ÷ 間隔が 512 を超えるとエラー）", C::Error},
    {K::ParallelPlanes, "parallelPlanes.offset", T::Float, -100000, 100000, "m", "位置", "法線方向の位置", C::Error},
    {K::ParallelPlanes, "parallelPlanes.variation", T::Float, 0, 1, "比", "間隔のばらつき", "各面を間隔の ±45% の範囲でずらす", C::Error},
    {K::ParallelPlanes, "parallelPlanes.seed", T::Int, 0, N, "", "Seed", "", C::None},
    {K::VolumeCrack, "volumeCrack.width", T::Float, 0, 0.2, kLongest, "幅",
     "表面での割れ目の全幅。To Volume のセル（最長辺 ÷ 解像度）より細いと消える", C::Error},
    {K::VolumeCrack, "volumeCrack.depth", T::Float, 0.01, 1, kLongest, "深さ",
     "表面から内側への深さ（V 字の断面）。1 で貫通して割る。浅くても面が外面に近いと薄片が分離する", C::Error},
    {K::VolumeCrack, "volumeCrack.variation", T::Float, 0, 1, "比", "ばらつき", "割れ目ごとの幅のばらつき", C::Error},
    {K::VolumeCrack, "volumeCrack.noise", T::Float, 0, 1, "比", "ゆらぎ", "割れ目に沿った幅のゆらぎ", C::Error},
    {K::VolumeCrack, "volumeCrack.noiseScale", T::Float, 0.5, 16, "最長辺あたりの山の数", "ゆらぎの細かさ", "", C::Error},
    {K::VolumeCrack, "volumeCrack.seed", T::Int, 0, N, "", "Seed", "", C::None},
    {K::VolumeCrack, "volumeCrack.source", T::Enum, N, N, "", "割り方",
     "inputs は Points か Planes の入力に沿って割る。shells は形をなめらかにした殻に沿って割る（Points・Planes は外す）",
     C::Clamp, kCrackSources},
    {K::VolumeCrack, "volumeCrack.shellSpacing", T::Float, 0.01, 0.5, kLongest, "殻の間隔", "shells 用。剥がれる板の厚さ", C::Error},
    {K::VolumeCrack, "volumeCrack.shellCount", T::Int, 1, 32, "枚", "殻の枚数", "shells 用。表面から何枚目まで割るか", C::Error},
    {K::VolumeCrack, "volumeCrack.shellSmoothing", T::Float, 0, 0.3, kLongest, "なめらかさ",
     "shells 用。殻の形を表面の細かな凹凸からならす半径", C::Error},
    {K::VolumeCrack, "volumeCrack.shellPeel", T::Float, 0, 1, "比", "剥がれ",
     "shells 用。一番外の板が剥がれ落ちている割合（内側ほど剥がれにくい）。まだらの大きさは noiseScale。0 だと殻は表面に出ず見えない", C::Error},
    {K::VolumeCrack, "volumeCrack.extent", T::Float, 0, 1, kLongest, "割れ目の長さ",
     "Planes 入力用。0 で面全体が割れ目（端から端まで続く）。正なら面をこの長さのセルに分け、セルごとに先端の閉じた楕円の割れ目を置く（途中で止まる節理）", C::Error},
    {K::VolumeCrack, "volumeCrack.coverage", T::Float, 0, 1, "比", "割れている割合",
     "Planes 入力で extent > 0 のとき。割れ目を置くセルの割合。0 なら何も彫らない", C::Error},
    {K::VolumeCrack, "volumeCrack.stagger", T::Float, 0, 1, "面の間隔 × ±0.45 に対する比", "段違い",
     "Planes 入力で extent > 0 のとき。割れ目ごとに面の法線方向へずらし、段違い（雁行）の節理にする", C::Error},
    {K::VolumeNoise, "volumeNoise.type", T::Enum, N, N, "", "種類", "", C::Clamp, kNoiseTypes},
    {K::VolumeNoise, "volumeNoise.amount", T::Float, 0, 0.2, kLongest, "量", "削る深さの最大。内側へだけ削る", C::Error},
    {K::VolumeNoise, "volumeNoise.scale", T::Float, 0.5, 64, "最長辺あたりの山の数", "細かさ", "", C::Error},
    {K::VolumeNoise, "volumeNoise.octaves", T::Int, 1, 5, "", "重ねる数", "", C::Error},
    {K::VolumeNoise, "volumeNoise.warp", T::Float, 0, 0.2, kLongest, "歪み", "サンプル位置をずらす量", C::Error},
    {K::VolumeNoise, "volumeNoise.warpScale", T::Float, 0.5, 16, "最長辺あたりの山の数", "歪みの細かさ", "", C::Error},
    {K::VolumeNoise, "volumeNoise.seed", T::Int, 0, N, "", "Seed", "", C::None},
    {K::VolumeSmooth, "volumeSmooth.mode", T::Enum, N, N, "", "モード", "", C::Clamp, kSmoothModes},
    {K::VolumeSmooth, "volumeSmooth.radius", T::Float, 0.005, 0.2, kLongest, "半径", "ぼかしの幅（σ）", C::Error},
    {K::VolumeSmooth, "volumeSmooth.amount", T::Float, 0, 1, "比", "量", "sharpen では 0〜1 が 0〜2 倍", C::Error},
    {K::VolumeSmooth, "volumeSmooth.upwardFocus", T::Float, 0, 1, "比", "向きに集中",
     "focusDirection を向いた面ほど強く効かせる（既定の向きは上）", C::Error},
    {K::VolumeSmooth, "volumeSmooth.focusDirection", T::Float3, N, N, "向き（正規化しなくてよい）", "集中する向き",
     "既定 [0,1,0]（上）。風上・氷河の流れてきた側を向けると、その側だけを丸く研磨する（羊背岩・風食）", C::None},
    {K::VolumeTerrace, "volumeTerrace.step", T::Float, 0.02, 1, kLongest, "段の間隔", "層の厚さ", C::Error},
    {K::VolumeTerrace, "volumeTerrace.depth", T::Float, 0, 0.2, kLongest, "深さ", "段のへこみの深さ", C::Error},
    {K::VolumeTerrace, "volumeTerrace.ratio", T::Float, 0.05, 0.95, "比", "へこむ割合", "各層のうちへこむ部分", C::Error},
    {K::VolumeTerrace, "volumeTerrace.softness", T::Float, 0, 0.5, "段の間隔に対する比", "なだらかさ", "", C::Error},
    {K::VolumeTerrace, "volumeTerrace.variation", T::Float, 0, 1, "比", "ばらつき", "", C::Error},
    {K::VolumeTerrace, "volumeTerrace.noise", T::Float, 0, 1, "段の間隔に対する比", "ゆらぎ", "", C::Error},
    {K::VolumeTerrace, "volumeTerrace.noiseScale", T::Float, 0.5, 16, "最長辺あたりの山の数", "ゆらぎの細かさ", "", C::Error},
    {K::VolumeTerrace, "volumeTerrace.rotation", T::Float3, N, N, "度", "向き", "回転した +Y が層の法線", C::Error},
    {K::VolumeTerrace, "volumeTerrace.seed", T::Int, 0, N, "", "Seed", "", C::None},
    {K::VolumeClose, "volumeClose.mode", T::Enum, N, N, "", "モード", "", C::Clamp, kCloseModes},
    {K::VolumeClose, "volumeClose.width", T::Float, 0.005, 0.3, kLongest, "幅", "width モード用。この幅より狭い隙間を埋める", C::Error},
    {K::VolumeClose, "volumeClose.distance", T::Float, 0.01, 1, kLongest, "距離", "occlusion モード用。遮蔽を調べるレイの長さ", C::Error},
    {K::VolumeClose, "volumeClose.threshold", T::Float, 0.5, 1, "遮蔽率", "しきい値", "occlusion モード用。これより奥まった所を埋める", C::Error},
    {K::VolumeClose, "volumeClose.samples", T::Int, 8, 128, "本", "サンプル数", "", C::Error},
    {K::VolumeClose, "volumeClose.softness", T::Float, 0.02, 0.5, "遮蔽率の幅", "なだらかさ", "", C::Error},
    {K::VolumeEdgeWear, "volumeEdgeWear.radius", T::Float, 0.005, 0.2, kLongest, "半径", "稜線の丸まりの幅（σ）", C::Error},
    {K::VolumeEdgeWear, "volumeEdgeWear.amount", T::Float, 0, 0.2, kLongest, "量", "直角の稜線と頂点で削る深さ。鈍い稜線ほど浅い", C::Error},
    {K::VolumeEdgeWear, "volumeEdgeWear.noise", T::Float, 0, 1, "比", "ばらつき", "", C::Error},
    {K::VolumeEdgeWear, "volumeEdgeWear.noiseScale", T::Float, 0.5, 16, "最長辺あたりの山の数", "ばらつきの細かさ", "", C::Error},
    {K::VolumeEdgeWear, "volumeEdgeWear.upwardFocus", T::Float, 0, 1, "比", "向きに集中",
     "focusDirection を向いた面の稜線ほど強く削る（既定の向きは上）", C::Error},
    {K::VolumeEdgeWear, "volumeEdgeWear.focusDirection", T::Float3, N, N, "向き（正規化しなくてよい）", "集中する向き",
     "既定 [0,1,0]（上）", C::None},
    {K::VolumeEdgeWear, "volumeEdgeWear.seed", T::Int, 0, N, "", "Seed", "", C::None},
    {K::VolumeClip, "volumeClip.mode", T::Enum, N, N, "", "モード",
     "ground にすると原点中心の形（Random Boxes・Base Shape）も持ち上げずに地面へ据えられる", C::Clamp, kClipModes},
    {K::VolumeClip, "volumeClip.height", T::Float, -100000, 100000, "m", "高さ",
     "world はこの高さ（ワールド Y）の水平面で切る。ground は切り口（底面）をこの高さに置く", C::Error},
    {K::VolumeClip, "volumeClip.embed", T::Float, 0, 0.9, "形の高さに対する比", "埋める割合",
     "ground 用。形の底からこの割合の高さで切って捨てる（地面に埋まった部分）。0 で底をそのまま据える", C::Error},
    {K::VolumeClip, "volumeClip.invert", T::Bool, N, N, "", "反転", "false で下を捨てる、true で上を捨てる", C::None},
    {K::VolumeUndercut, "volumeUndercut.height", T::Float, 0, 1, "形の高さに対する位置", "高さ",
     "最初の帯の中心。底 0、上 1（内部の格子点の範囲）。きのこ岩は 0.15〜0.3", C::Error},
    {K::VolumeUndercut, "volumeUndercut.width", T::Float, 0.02, 1, "形の高さに対する比", "帯の幅", "帯の半分の高さ", C::Error},
    {K::VolumeUndercut, "volumeUndercut.depth", T::Float, 0, 0.4, kLongest, "深さ",
     "帯の中心で内側へ削る深さ。帯の高さでの形の半分の太さを超えると上下に切り離され、エラーになる", C::Error},
    {K::VolumeUndercut, "volumeUndercut.count", T::Int, 1, 8, "本", "帯の数", "上へ繰り返す（フードゥーの段）", C::Error},
    {K::VolumeUndercut, "volumeUndercut.spacing", T::Float, 0.05, 1, "形の高さに対する比", "間隔", "帯の間隔", C::Error},
    {K::VolumeUndercut, "volumeUndercut.noise", T::Float, 0, 1, "比", "ばらつき", "削る深さを水平方向にばらつかせる", C::Error},
    {K::VolumeUndercut, "volumeUndercut.noiseScale", T::Float, 0.5, 16, "最長辺あたりの山の数", "ばらつきの細かさ", "", C::Error},
    {K::VolumeUndercut, "volumeUndercut.seed", T::Int, 0, N, "", "Seed", "", C::None},
    {K::VolumeScatter, "volumeScatter.shape", T::Enum, N, N, "", "形", "散らす形", C::Clamp, kScatterShapes},
    {K::VolumeScatter, "volumeScatter.operation", T::Enum, N, N, "", "合成", "", C::Clamp, kScatterOperations},
    {K::VolumeScatter, "volumeScatter.count", T::Int, 1, 2000, "個", "数", "置けた分だけ置く（表面の近くに置ける場所が足りないと減る）", C::Error},
    {K::VolumeScatter, "volumeScatter.radiusMin", T::Float, 0.005, 0.3, kLongest, "半径 最小", "radiusMax 以下", C::Error},
    {K::VolumeScatter, "volumeScatter.radiusMax", T::Float, 0.005, 0.3, kLongest, "半径 最大",
     "To Volume のセル（最長辺 ÷ 解像度）の 2 倍より小さい形は潰れる", C::Error},
    {K::VolumeScatter, "volumeScatter.depthMin", T::Float, -1, 4, "その形の半径に対する比", "深さ 最小",
     "中心を置く深さ。表面から内側が正。礫は -0.3〜0.5（半分ほど突き出る）、気泡の穴は 0〜1.5。depthMax 以下", C::Error},
    {K::VolumeScatter, "volumeScatter.depthMax", T::Float, -1, 4, "その形の半径に対する比", "深さ 最大", "", C::Error},
    {K::VolumeScatter, "volumeScatter.elongation", T::Float, 1, 4, "比", "細長さ", "楕円体・箱の軸の長さの比の最大", C::Error},
    {K::VolumeScatter, "volumeScatter.blend", T::Float, 0, 1, "その形の半径に対する比", "なじませる幅",
     "形の境をなめらかにつなぐ（和では礫の根元が埋まったように、差では穴の縁が丸く）", C::Error},
    {K::VolumeScatter, "volumeScatter.seed", T::Int, 0, N, "", "Seed", "", C::None},
    // --- メッシュ ---
    {K::Decimate, "decimate.targetTriangles", T::Int, 64, 500000, "三角形", "目標の三角形数", "入力全体に対する数。評価で範囲へ丸める", C::Clamp},
    {K::Decimate, "decimate.maxError", T::Float, 0, 0.1, kLongest, "形のずれの上限", "0 で上限なし", C::Error},
    {K::Decimate, "decimate.creaseWeight", T::Float, 0, 10, "", "稜線の保護", "大きいほど稜線を残す", C::Error},
    {K::Remesh, "remesh.edgeLength", T::Float, 0.001, 0.2, kLongest, "辺の長さ", "作り直す三角形の辺の長さ", C::Clamp},
    {K::Remesh, "remesh.iterations", T::Int, 1, 20, "回", "繰り返し", "", C::Clamp},
    {K::Remesh, "remesh.featureAngle", T::Float, 0, 180, "度", "特徴辺の角度", "これより鋭い折れ目を稜線として残す", C::Clamp},
    {K::Subdivide, "subdivide.levels", T::Int, 0, 6, "段", "細分化の段階数", "1 段で三角形が 4 倍。400 万面まで", C::Error},
    {K::Subdivide, "subdivide.threshold", T::Float, 0, 1, "マスクの値", "マスクのしきい値", "Mask 接続時だけ使う", C::Clamp},
    {K::Displace, "displace.amount", T::Float, -10, 10, "m", "変位量", "(ハイト − midpoint) × amount だけ法線方向へ動かす。GPU の素材ハイトが要る", C::Error},
    {K::Displace, "displace.midpoint", T::Float, 0, 1, "ハイト", "基準ハイト", "変位 0 とみなすハイト", C::Error},
    {K::RockAsset, "rockAsset.lodCount", T::Int, 1, 6, "段", "LODの段数", "LOD0 を含む", C::Clamp},
    {K::RockAsset, "rockAsset.maxTriangles", T::Int, 64, 500000, "三角形", "LOD0の上限", "", C::Clamp},
    {K::RockAsset, "rockAsset.trianglePercent", T::FloatArray, 0.1, 100, "% (LOD0 に対して)", "LODnの割合", "[0] は使わない", C::Clamp},
    {K::RockAsset, "rockAsset.screenSize", T::FloatArray, 0.001, 4, "画面の高さに対する比", "LODnの切替", "[0] は使わない", C::Clamp},
    {K::RockAsset, "rockAsset.shareUv", T::BoolArray, N, N, "", "LODnのUV共有", "[0] は使わない。最初の false 以降は共有しない", C::None},
    // --- 素材とマスク ---
    {K::ApplyMaterial, "applyMaterial.heightBlend", T::Bool, N, N, "", "ハイトで合成", "素材のハイトが下地より高い所を前に出す", C::None},
    {K::ApplyMaterial, "applyMaterial.heightBlendRange", T::Float, 0.01, 1, "", "なだらかさ", "", C::Clamp},
    {K::ApplyMaterial, "applyMaterial.opacity", T::Float, 0, 1, "比", "不透明度", "", C::Clamp},
    {K::MaterialMask, "materialMask.texture", T::Int, N, N, "", "画像（R）", "文書の textures[] の id。null で一定値", C::None},
    {K::MaterialMask, "materialMask.value", T::Float, 0, 1, "比", "値・画像の強度", "", C::Clamp},
    {K::MaterialMask, "materialMask.repeatMeters", T::Float, 0.001, 10000, "m（UV では UV 単位）", "反復幅", "", C::Clamp},
    {K::MaterialMask, "materialMask.invert", T::Bool, N, N, "", "反転", "", C::None},
    {K::MaterialMask, "materialMask.triplanar", T::Bool, N, N, "", "Triplanar", "", C::None},
    {K::ShapeMask, "shapeMask.type", T::Enum, N, N, "", "種類", "", C::Clamp, kShapeMaskTypes},
    {K::ShapeMask, "shapeMask.resolution", T::Int, 128, 4096, "px（2 のべき乗）", "マスク解像度", "", C::Clamp},
    {K::ShapeMask, "shapeMask.low", T::Float, 0, 0.999, "0〜1", "下限", "", C::Clamp},
    {K::ShapeMask, "shapeMask.high", T::Float, 0.001, 1, "0〜1", "上限", "low より大きく", C::Clamp},
    {K::ShapeMask, "shapeMask.gamma", T::Float, 0.1, 10, "", "カーブ（ガンマ）", "", C::Clamp},
    {K::ShapeMask, "shapeMask.invert", T::Bool, N, N, "", "反転", "", C::None},
    {K::ShapeMask, "shapeMask.distance", T::Float, 0.001, 1000, "m", "距離 / 曲率スケール", "occlusion は探す距離、曲率は見る大きさ", C::Clamp},
    {K::ShapeMask, "shapeMask.samples", T::Int, 8, 128, "本", "サンプル数", "", C::Clamp},
    {K::StructureMask, "structureMask.type", T::Enum, N, N, "", "種類", "bands は Planes 入力が要る", C::Clamp, kStructureTypes},
    {K::StructureMask, "structureMask.resolution", T::Int, 128, 4096, "px（2 のべき乗）", "マスク解像度", "", C::Error},
    {K::StructureMask, "structureMask.fill", T::Float, 0, 1, "比", "塗る割合", "bands は層のうち白にする割合、veins は網目のうち残す割合（残りは途切れて閉じた網目にならない）", C::Error},
    {K::StructureMask, "structureMask.softness", T::Float, 0, 1, "比", "ぼかし", "bands は層の境（間隔に対する比）、veins は線の縁", C::Error},
    {K::StructureMask, "structureMask.scale", T::Float, 0.01, 100, "m", "網目の大きさ", "veins 用", C::Error},
    {K::StructureMask, "structureMask.width", T::Float, 0.005, 0.5, "網目に対する比", "線の幅", "veins 用", C::Error},
    {K::StructureMask, "structureMask.warp", T::Float, 0, 1, "比", "ゆがみ", "bands は間隔、veins は網目に対する比", C::Error},
    {K::StructureMask, "structureMask.warpScale", T::Float, 0.01, 100, "m", "ゆがみの大きさ", "", C::Error},
    {K::StructureMask, "structureMask.seed", T::Int, 0, N, "", "Seed", "", C::None},
    {K::StructureMask, "structureMask.invert", T::Bool, N, N, "", "反転", "", C::None},
    {K::NoiseMask, "noiseMask.size", T::Float, 0.001, 1000, "m", "ムラの大きさ", "", C::Clamp},
    {K::NoiseMask, "noiseMask.contrast", T::Float, 0, 1, "比", "コントラスト", "", C::Clamp},
    {K::NoiseMask, "noiseMask.detail", T::Float, 0, 1, "比", "細部", "", C::Clamp},
    {K::NoiseMask, "noiseMask.warp", T::Float, 0, 1, "比", "歪み", "", C::Clamp},
    {K::NoiseMask, "noiseMask.resolution", T::Int, 128, 4096, "px（2 のべき乗）", "マスク解像度", "", C::Clamp},
    {K::NoiseMask, "noiseMask.invert", T::Bool, N, N, "", "反転", "", C::None},
    {K::NoiseMask, "noiseMask.seed", T::Int, 0, N, "", "Seed", "", C::None},
    {K::DepositionMask, "depositionMask.amount", T::Float, 0, 1, "比", "堆積量", "", C::Error},
    {K::DepositionMask, "depositionMask.distance", T::Float, 0.001, 1000, "m", "隙間の範囲", "", C::Error},
    {K::DepositionMask, "depositionMask.maxSlopeDegrees", T::Float, 1, 89, "度（水平から）", "許容する傾斜", "これより急な面には溜まらない", C::Error},
    {K::DepositionMask, "depositionMask.recessPreference", T::Float, 0, 1, "比", "隙間を優先", "", C::Error},
    {K::DepositionMask, "depositionMask.resolution", T::Int, 128, 4096, "px（2 のべき乗）", "マスク解像度", "", C::Error},
    {K::DepositionMask, "depositionMask.samples", T::Int, 8, 128, "本", "サンプル数", "", C::Error},
    {K::DepositionMask, "depositionMask.invert", T::Bool, N, N, "", "反転", "", C::None},
    {K::MaskCombine, "maskCombine.operation", T::Enum, N, N, "", "演算", "", C::Clamp, kCombineOps},
    {K::MaskCombine, "maskCombine.mix", T::Float, 0, 1, "0 = A, 1 = B", "混合", "mix 用", C::Clamp},
    {K::MaskCombine, "maskCombine.low", T::Float, 0, 0.999, "0〜1", "下限", "", C::Clamp},
    {K::MaskCombine, "maskCombine.high", T::Float, 0.001, 1, "0〜1", "上限", "low より大きく", C::Clamp},
    {K::MaskCombine, "maskCombine.gamma", T::Float, 0.1, 10, "", "カーブ（ガンマ）", "", C::Clamp},
    {K::MaskCombine, "maskCombine.invert", T::Bool, N, N, "", "反転", "", C::None},
    {K::MaskFilter, "maskFilter.type", T::Enum, N, N, "", "種類", "", C::Clamp, kFilterTypes},
    {K::MaskFilter, "maskFilter.radius", T::Float, 0.001, 1, "m（表面上）", "半径", "", C::Clamp},
    {K::MaskFilter, "maskFilter.amount", T::Float, 0, 4, "", "量", "sharpen 用", C::Clamp},
    {K::MaskFilter, "maskFilter.inputLow", T::Float, 0, 0.999, "0〜1", "入力の黒", "", C::Clamp},
    {K::MaskFilter, "maskFilter.inputHigh", T::Float, 0.001, 1, "0〜1", "入力の白", "inputLow より大きく", C::Clamp},
    {K::MaskFilter, "maskFilter.gamma", T::Float, 0.1, 10, "", "カーブ（ガンマ）", "", C::Clamp},
    {K::MaskFilter, "maskFilter.outputLow", T::Float, 0, 1, "0〜1", "出力の黒", "", C::Clamp},
    {K::MaskFilter, "maskFilter.outputHigh", T::Float, 0, 1, "0〜1", "出力の白", "", C::Clamp},
    {K::MaskFilter, "maskFilter.invert", T::Bool, N, N, "", "反転", "", C::None},
    // --- Surface（素材のレイヤー） ---
    {K::Surface, "layer.material", T::Int, N, N, "", "マテリアル", "文書の materials[] の id。null で下の定数色で塗る", C::None},
    {K::Surface, "layer.name", T::String, N, N, "", "名前", "", C::None},
    {K::Surface, "layer.enabled", T::Bool, N, N, "", "有効", "", C::None},
    {K::Surface, "layer.channels", T::Enum, N, N, "", "チャンネル", "塗るチャンネルの配列", C::None, kChannels},
    {K::Surface, "layer.baseColor", T::Float3, 0, 1, "リニア RGB", "ベースカラー", "material が null のときだけ使う", C::None},
    {K::Surface, "layer.roughness", T::Float, 0, 1, "0〜1", "ラフネス", "material が null のときだけ使う", C::None},
    {K::Surface, "layer.metallic", T::Float, 0, 1, "0〜1", "メタルネス", "material が null のときだけ使う", C::None},
    {K::Surface, "layer.ambientOcclusion", T::Float, 0, 1, "0〜1", "AO", "material が null のときだけ使う", C::None},
    {K::Surface, "layer.height.source", T::Enum, N, N, "", "ハイトの元", "", C::Clamp, kValueSources},
    {K::Surface, "layer.height.base", T::Float, N, N, "", "ハイトの基準", "", C::None},
    {K::Surface, "layer.height.gain", T::Float, N, N, "", "ハイトの強さ", "", C::None},
    {K::Surface, "layer.height.noise.type", T::Enum, N, N, "", "ノイズの種類", "", C::Clamp, kLayerNoiseTypes},
    {K::Surface, "layer.height.noise.scale", T::Float, N, N, "", "ノイズの細かさ", "", C::None},
    {K::Surface, "layer.height.noise.amount", T::Float, N, N, "", "ノイズの量", "", C::None},
    {K::Surface, "layer.height.noise.octaves", T::Int, N, N, "", "ノイズの重ねる数", "", C::None},
    {K::Surface, "layer.height.noise.offset", T::Float, N, N, "", "ノイズのずらし", "", C::None},
    {K::Surface, "layer.uvScale", T::Float, N, N, "", "UV の倍率", "", C::None},
    {K::Surface, "layer.mapping.method", T::Enum, N, N, "", "方式", "", C::Clamp, kMappingMethods},
    {K::Surface, "layer.mapping.repeatMeters", T::Float, 0.001, 10000, "m", "反復サイズ", "Triplanar でテクスチャ 1 枚が覆う大きさ", C::Clamp},
    {K::Surface, "layer.mapping.offset", T::Float3, N, N, "m", "ずらし", "", C::None},
    {K::Surface, "layer.mapping.rotationDegrees", T::Float3, N, N, "度", "回転", "", C::None},
    {K::Surface, "layer.mapping.sharpness", T::Float, 1, 16, "", "混合の鋭さ", "Triplanar の 3 方向の混ぜ方", C::Clamp},
    // --- モデル ---
    {K::Model, "model.model", T::Int, N, N, "", "モデル", "文書の models[] の id", C::None},
    {K::Model, "model.position", T::Float3, N, N, "m", "位置", "モデルの底面の中心", C::None},
    {K::Model, "model.rotation", T::Float3, N, N, "度", "回転", "Z → X → Y", C::None},
    {K::Model, "model.scale", T::Float, 0, N, "倍", "倍率", "0 以下は 1 になる", C::Clamp},
    {K::Transform, "transform.position", T::Float3, N, N, "m", "位置", "倍率 → 回転 → 移動（原点まわり）", C::None},
    {K::Transform, "transform.rotation", T::Float3, N, N, "度", "回転", "", C::None},
    {K::Transform, "transform.scale", T::Float, 0, N, "倍", "倍率", "0 以下は 1 になる", C::Clamp},
    // --- 山グラフ ---
    {K::Heightmap, "heightmap.source", T::Enum, N, N, "", "種類", "", C::Clamp, kHeightmapSources},
    {K::Heightmap, "heightmap.image", T::String, N, N, "", "画像", "シーンからの相対パス（16bit PNG 推奨、8bit、EXR）", C::None},
    {K::Heightmap, "heightmap.width", T::Float, 1, 10000, "m", "幅", "X 方向", C::Clamp},
    {K::Heightmap, "heightmap.depth", T::Float, 1, 10000, "m", "奥行き", "Z 方向", C::Clamp},
    {K::Heightmap, "heightmap.minHeight", T::Float, -10000, 10000, "m", "最低の高さ", "maxHeight より低く", C::Error},
    {K::Heightmap, "heightmap.maxHeight", T::Float, -10000, 10000, "m", "最高の高さ", "minHeight より高く", C::Error},
    {K::Heightmap, "heightmap.resolution", T::Int, 16, 1024, "分割", "格子の細かさ", "三角形は 2 × resolution²", C::Clamp},
    {K::Heightmap, "heightmap.textureResolution", T::Int, 128, 4096, "px（2 のべき乗）", "テクスチャ解像度", "", C::Error},
    {K::Heightmap, "heightmap.featureSize", T::Float, 0.1, N, "m", "起伏の大きさ", "", C::Error},
    {K::Heightmap, "heightmap.roughness", T::Float, 0, 1, "比", "荒さ", "", C::Clamp},
    {K::Heightmap, "heightmap.peak", T::Float, 0, 1, "比", "山の形", "", C::Clamp},
    {K::Heightmap, "heightmap.seed", T::Int, 0, N, "", "Seed", "", C::None},
    {K::Rock, "rock.scene", T::String, N, N, "", "岩グラフ", ".rockgraph のパス（シーンからの相対）。焼いた岩アセットを読む", C::None},
    {K::Rock, "rock.scale", T::Float, 0.001, 1000, "倍", "倍率", "", C::Clamp},
    {K::Rock, "rock.weight", T::Float, 0, 1000, "", "重み", "Rock Scatter で選ばれる相対的な重み", C::Clamp},
    {K::RockScatter, "rockScatter.spacing", T::Float, 0.05, 10000, "m", "間隔", "岩の中心どうしの最小距離", C::Clamp},
    {K::RockScatter, "rockScatter.maxCount", T::Int, 1, 50000, "個", "上限の数", "", C::Clamp},
    {K::RockScatter, "rockScatter.scaleMin", T::Float, 0.01, 100, "倍", "最小の倍率", "scaleMax 以下", C::Clamp},
    {K::RockScatter, "rockScatter.scaleMax", T::Float, 0.01, 100, "倍", "最大の倍率", "", C::Clamp},
    {K::RockScatter, "rockScatter.alignToNormal", T::Float, 0, 1, "比", "法線に合わせる", "0 で真上、1 で地形の法線に沿う", C::Clamp},
    {K::RockScatter, "rockScatter.embed", T::Float, 0, 0.9, "岩の高さに対する比", "沈める量", "", C::Clamp},
    {K::RockScatter, "rockScatter.seed", T::Int, 0, N, "", "Seed", "", C::None},
};

constexpr const char* kKeepsLargest =
    "浮いた小片を捨てる: 加工で新しく切り離された小片は入力の塊ごとに最大のものだけ残す。入力の時点で分かれていた塊は"
    "それぞれ残すが、最大の塊の 1% 未満は捨てる。岩を 1 つの塊にしたいなら、先に Volume Close で繋ぐ";

constexpr NodeSummary kSummaries[] = {
    {K::Surface, "素材のレイヤー（マテリアルとマッピング）。Apply Material の Material へ繋ぐ", ""},
    {K::MeshOutput, "最終出力。Geometry に表示するもの、Material に下地の素材を繋ぐ", "グラフに 1 つ置く"},
    {K::Merge, "複数の Mesh / Model の枝をまとめる", ""},
    {K::Model, "外部モデル（.model）を 1 つ置く", "岩グラフの形の生成には使わない"},
    {K::Transform, "上流のモデルをまとめて動かす", ""},
    {K::BaseRock, "母岩の基本形（Box など）の Mesh を作る", "ボリュームで加工するなら To Volume へ繋ぐ"},
    {K::RandomBoxes, "ランダムに重ねた直方体の塊を作る", "塊状の岩の出発点。To Volume へ繋いで一体化する"},
    {K::ToVolume, "Mesh（や Pieces to Mesh の結果）をボリューム（符号付き距離の格子）へ変換する",
     "解像度は 16〜128。セルより細い隙間は埋まる。接した片どうしの間に閉じた空洞が多数できることがある（害は少ない）"},
    {K::VolumeToMesh, "ボリュームをメッシュへ戻す", "岩には method を dualContouring にする"},
    {K::VolumeTransform, "ボリュームを動かす・回す・拡大する", ""},
    {K::UvUnwrap, "メッシュの UV を自動展開する", "Decimate で減らした後に置く。マスクと Material Bake は UV が要る"},
    {K::MaterialBake, "素材と形状 AO をテクスチャへ焼く。High にハイポリを繋ぐと細部を法線へ焼く",
     "GPU で焼く（rock_cli では焼けない）。Mesh にローポリ（UV 付き）、Material は未使用、High にハイポリ"},
    {K::ScatterPoints, "Mesh / Pieces の内部に点を撒く（Voronoi Fracture 用）", ""},
    {K::VoronoiFracture, "Mesh / Pieces を点の Voronoi（Points）か構造面の系統（Planes）で割ってピースの集まりにする",
     "Points と Planes のどちらか一方だけを繋ぐ。Planes は全系統の面で節理のブロックに割る（凸な Mesh だけ。rotation / stretch は使わない）。Pieces 入力は Points で片ごとに独立して割る"},
    {K::PieceSelect, "ピースを選ぶ（外面・範囲・体積・ランダム・縁・外周からの侵食）",
     "Piece Filter の Selection へ繋ぐ。Peel は Voronoi 直後のピース（Piece Transform より前）に使う。地面から生えた岩は grounded（接地）で根元を残し、支えを失った片を落とす"},
    {K::PieceFilter, "選んだピースを残す / 消す", "Pieces と Selection の両方に繋ぐ（Selection は同じピースから作ったもの）"},
    {K::PieceTransform, "選んだピースを動かす", ""},
    {K::PiecesToMesh, "ピースを 1 つのメッシュにまとめる", "面の溶接はしない。一体の形にするなら To Volume へ繋ぐ"},
    {K::ApplyMaterial, "メッシュに素材を貼る。Mask で範囲を決める", "Mesh には UV が要る（Triplanar なら不要）"},
    {K::MaterialMask, "画像か一定値のマスク", ""},
    {K::VolumeBoolean, "2 つのボリュームの和・交差・差", "A の格子が基準"},
    {K::PlaneCuts, "平面の群でボリュームを切り落とし、角張った面を作る", kKeepsLargest},
    {K::VolumeCrack, "構造面（Planes）か点の Voronoi 境界（Points）、または表面に沿う殻に沿って、表面から割れ目を彫る",
     "Points と Planes のどちらか一方だけを繋ぐ（source: shells なら両方外す）。深い割れ目や外面に近い面は岩を複数の塊に分ける（塊は残す）"},
    {K::VolumeNoise, "ボリュームの表面をノイズで削る", kKeepsLargest},
    {K::Decimate, "形を保って三角形を減らす", "UV Unwrap の前に置く"},
    {K::Subdivide, "三角形を細分化する（Displace の前）", ""},
    {K::Displace, "素材のハイトでメッシュの頂点を動かす", "GPU で作る素材ハイトが要る（rock_cli では評価できない）"},
    {K::ShapeMask, "形状（遮蔽・上向き・高さ・曲率）から UV のマスクを作る", "UV 付きの Mesh が要る"},
    {K::MaskCombine, "2 つのマスクを合成する", ""},
    {K::VolumeSmooth, "ボリュームの表面をなまらせる / 角を立てる", kKeepsLargest},
    {K::VolumeTerrace, "ある方向の層状の段（棚）を作る", kKeepsLargest},
    {K::VolumeClose, "狭い隙間・奥まった所を埋める", "割れ目で分かれた塊を繋ぎ直すのにも使える"},
    {K::Remesh, "三角形を一様な大きさに作り直す", "閉じた向き付きのメッシュが要る"},
    {K::VolumeEdgeWear, "凸な稜線と角だけを削って丸める（角の摩耗）", kKeepsLargest},
    {K::ParallelPlanes, "平行な構造面の群（節理・片理・層理）を定義する。Volume Crack / Voronoi Fracture / Structure Mask の Planes へ繋ぐ",
     "Planes 入力に別の Parallel Planes を繋ぐと、上流の系統にこの系統を足して渡す（節理系 1 → 2 → 3、8 系統まで）。Structure Mask は最初の系統で縞を塗る"},
    {K::LayeredBoxes, "平行な薄板の積層（層番号つきのピース）を作る",
     "板状・片理状の岩の出発点。Scatter Points と Voronoi Fracture の両方に繋ぐ"},
    {K::NoiseMask, "表面の 3D 座標からムラのマスクを作る", "UV 付きの Mesh が要る"},
    {K::StructureMask, "岩の構造から素材の模様のマスクを作る（構造面に沿う縞、網目の脈）",
     "UV 付きの Mesh が要る。縞は形の割れ目に使ったのと同じ Parallel Planes を Planes に繋ぐと向きが揃う。Apply Material の Mask へ"},
    {K::DepositionMask, "土が溜まりそうな所（窪み・緩い面）のマスクを作る", "UV 付きの Mesh が要る"},
    {K::MaskFilter, "マスクをぼかす・シャープにする・レベル補正する", ""},
    {K::VolumeUndercut, "形の高さの帯を内側へ削り、くびれを作る（きのこ岩・フードゥー・波食ノッチ）",
     "高さは形に対する位置（接地の前後で意味が変わらない）。削り落とされた小片は捨てる"},
    {K::VolumeScatter, "表面の近くに小さな形を散らし、和（埋まった礫）か差（穴・気泡）で合成する",
     "礫岩・角礫岩・多孔質の溶岩に使う。和で突き出す分だけ格子を広げる（各軸 256 点まで）。浮いた形は除く"},
    {K::VolumeClip, "水平面でボリュームを切り、片側を捨てる（接地面を作る）",
     "mode: ground で、原点中心の形を持ち上げずに地面へ据えられる。分かれた塊は残す"},
    {K::RockAsset, "岩グラフの最終段。LOD を作り、岩アセットにする", "Material Bake の後に置く"},
    {K::Heightmap, "山グラフの地形（ハイトマップの格子メッシュ）", "山グラフ専用"},
    {K::Rock, "山グラフ。岩グラフ（焼いた岩アセット）を 1 つ読む", "山グラフ専用。先に岩グラフで岩アセットを焼く"},
    {K::RockScatter, "山グラフ。地形に Rock を間隔を空けて撒く", "山グラフ専用"},
};

}  // namespace

std::span<const ParamDefinition> NodeParams() { return kParams; }
std::span<const NodeSummary> NodeSummaries() { return kSummaries; }

const NodeSummary* FindNodeSummary(NodeKind kind) {
    for (const NodeSummary& summary : kSummaries)
        if (summary.kind == kind) return &summary;
    return nullptr;
}

}  // namespace rock::graph
